//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMMapiTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chats
    {
        public Chats()
        {
            this.Messages = new HashSet<Messages>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OwnerId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
    }
}
