//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMMapiTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meets
    {
        public Meets()
        {
            this.UsersAndMeets = new HashSet<UsersAndMeets>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime MeetDateTime { get; set; }
        public string Event { get; set; }
        public string Adress { get; set; }
        public int OwnerId { get; set; }
        public decimal PeopleNumber { get; set; }
        public string Comment { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<UsersAndMeets> UsersAndMeets { get; set; }
    }
}
