//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMMapiTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public int ChatId { get; set; }
        public int FromUserId { get; set; }
        public string Text { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsReaded { get; set; }
    
        public virtual Chats Chats { get; set; }
    }
}
