//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMMapiTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Chats = new HashSet<Chats>();
            this.Friends = new HashSet<Friends>();
            this.Friends1 = new HashSet<Friends>();
            this.Meets = new HashSet<Meets>();
            this.UsersAndMeets = new HashSet<UsersAndMeets>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> NewMessagesCount { get; set; }
        public Nullable<int> FriendsCount { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Chats> Chats { get; set; }
        public virtual ICollection<Friends> Friends { get; set; }
        public virtual ICollection<Friends> Friends1 { get; set; }
        public virtual ICollection<Meets> Meets { get; set; }
        public virtual ICollection<UsersAndMeets> UsersAndMeets { get; set; }
    }
}
